name: Selenium CI with Allure Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Step 4: Install Allure
        run: |
          # Fetch the latest Allure release URL
          $LATEST_URL = (Invoke-RestMethod -Uri https://api.github.com/repos/allure-framework/allure2/releases/latest).assets | Where-Object { $_.name -like "*.zip" } | Select-Object -ExpandProperty browser_download_url
          
          # Download Allure
          Invoke-WebRequest -Uri $LATEST_URL -OutFile allure.zip
          
          # Verify the file size
          if ((Get-Item allure.zip).length -lt 100000) {
            Write-Host "Error: Downloaded file size is too small, indicating a failed download."
            exit 1
          }
          
          # Unzip Allure
          Expand-Archive -Path allure.zip -DestinationPath allure
          
          # Move Allure to C:\Allure
          Move-Item -Path allure -Destination C:\Allure

      # Step 5: Verify Allure installation
        run: |
          # List files in the C:\Allure directory for debugging
          Get-ChildItem -Path C:\Allure -Recurse
          
          # Check if the Allure binary exists
          if (Test-Path "C:\Allure\allure-*/bin/allure") {
            Write-Host "Allure is successfully installed."
          } else {
            Write-Host "Error: Allure is not installed properly."
            exit 1
          }

      # Step 6: Run Selenium Tests and Generate Allure Results
        run: pytest test_cases/test_login.py --alluredir=reports/allure-report --html=reports/report.html

      # Step 7: Generate Allure Report
        run: |
          C:\Allure\allure-*/bin\allure generate reports/allure-report --clean -o allure-report
        shell: pwsh

      # Step 8: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
